guess_dict ={
"Almond": "A type of tree nut known for its mild, nutty flavor.",
"Apples": "Round fruit with various colors and flavors, often used in pies and snacks.",
"Banana": "A long, curved fruit with a sweet taste and yellow skin.",
"Brazil": "A South American country known for its vast rainforests and diverse wildlife.",
"Carrot": "A long, orange vegetable known for its crunchy texture and sweet taste.",
"Cashew": "A kidney-shaped nut often used in cooking and snacking.",
"Cherry": "A small, red or black fruit with a sweet and tart flavor.",
"Chocho": "A type of legume also known as 'chayote' or 'vegetable pear.'",
"Dimple": "A small indentation or natural dent, often on the cheeks.",
"Double": "Twice the amount or size of something.",
"Enough": "An adequate or sufficient quantity or degree of something.",
"Entire": "Whole or complete, without any missing parts.",
"Fabric": "Material or textile used in making clothing or other products.",
"Garlic": "A pungent bulbous plant used as a flavoring in cooking.",
"Greens": "Leafy vegetables, often used in salads or as side dishes.",
"Gadget": "A small, innovative device designed to perform specific tasks.",
"Labour": "Work or effort, often associated with manual or physical tasks.",
"Lichee": "A tropical fruit with a sweet and juicy flesh.",
"Logged": "Recorded or documented, typically in a systematic manner.",
"Marrow": "The soft, inner part of certain vegetables, like squash.",
"Madrid": "The capital city of Spain, known for its rich culture and history.",
"Nettle": "A plant with stinging hairs, known for its medicinal and culinary uses.",
"Orange": "A citrus fruit with a vibrant, orange-colored skin and a tangy flavor.",
"Oyster": "A type of shellfish often enjoyed as a delicacy.",
"Papaya": "A tropical fruit with sweet, orange flesh and black seeds.",
"Peanut": "A legume known for its nutritious and tasty seeds.",
"Pepper": "A spice derived from dried, ground peppers, used for flavoring.",
"Potato": "A starchy tuber vegetable used in various culinary dishes.",
"Quince": "A fruit with a tart taste, often used in preserves and desserts.",
"Radish": "A small, crunchy vegetable with a peppery flavor.",
"Rocket": "A leafy green vegetable, also known as arugula, with a peppery taste.",
"Squash": "A type of vegetable known for its diverse varieties and culinary uses.",
"Tomato": "A red or yellowish fruit often used as a vegetable in cooking.",
"Wakame": "A type of edible seaweed commonly used in Asian cuisine.",
"Walnut": "A nutritious tree nut with a hard shell and a distinctive flavor.",
}